# Generated by Django 4.2.2 on 2023-07-05 05:59

import api.model_validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DecisionTreeCR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=128, unique=True)),
                (
                    "tree",
                    models.JSONField(
                        validators=[
                            api.model_validators.DecisionTreeValidator.validate_tree
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QueueCR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=128, unique=True)),
                (
                    "prioritization_function",
                    models.JSONField(blank=True, default=None, null=True),
                ),
                (
                    "decision_tree",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.decisiontreecr",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReviewCR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                (
                    "entity_id",
                    models.CharField(
                        blank=True, default=None, max_length=128, null=True
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[("text", "Text"), ("image", "Image")], max_length=128
                    ),
                ),
                ("entity_content", models.TextField()),
                (
                    "entity_create_time",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "entity_metadata",
                    models.JSONField(blank=True, default=None, null=True),
                ),
                (
                    "user_id",
                    models.CharField(
                        blank=True, default=None, max_length=128, null=True
                    ),
                ),
                (
                    "user_name",
                    models.CharField(
                        blank=True, default=None, max_length=128, null=True
                    ),
                ),
                (
                    "user_email",
                    models.CharField(
                        blank=True, default=None, max_length=128, null=True
                    ),
                ),
                (
                    "user_phone_number",
                    models.CharField(
                        blank=True, default=None, max_length=128, null=True
                    ),
                ),
                (
                    "user_metadata",
                    models.JSONField(blank=True, default=None, null=True),
                ),
                (
                    "questions_with_answers",
                    models.JSONField(blank=True, default=None, null=True),
                ),
                ("score", models.FloatField(blank=True, default=None, null=True)),
                (
                    "queue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.queuecr"
                    ),
                ),
            ],
        ),
    ]
