# Generated by Django 4.2.2 on 2023-07-01 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionTreeCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(verbose_name=128)),
                ('tree', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='QueueCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(verbose_name=128)),
                ('prioritization_function', models.JSONField(blank=True, default=None, null=True)),
                ('decision_tree', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.decisiontreecr')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('entity_id', models.CharField(blank=True, default=None, null=True, verbose_name=128)),
                ('entity_type', models.CharField(blank=True, default=None, null=True, verbose_name=128)),
                ('entity_content', models.TextField()),
                ('entity_create_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('entity_metadata', models.JSONField(blank=True, default=None, null=True)),
                ('user_id', models.CharField(blank=True, default=None, null=True, verbose_name=128)),
                ('user_name', models.CharField(blank=True, default=None, null=True, verbose_name=128)),
                ('user_email', models.CharField(blank=True, default=None, null=True, verbose_name=128)),
                ('user_phone_number', models.CharField(blank=True, default=None, null=True, verbose_name=128)),
                ('user_metadata', models.JSONField(blank=True, default=None, null=True)),
                ('questions_with_answers', models.JSONField(blank=True, default=None, null=True)),
                ('score', models.FloatField(blank=True, default=None, null=True)),
                ('queue', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.queuecr')),
            ],
        ),
    ]
