# Generated by Django 4.2.2 on 2023-07-05 23:43

import api.model_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewcr',
            name='questions_with_answers',
            field=models.JSONField(blank=True, default=None, null=True, validators=[api.model_validators.ReviewValidator.validate_questions_with_answers]),
        ),
    ]
