# Generated by Django 4.2.2 on 2023-07-04 16:33

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisiontreecr',
            name='name',
            field=models.CharField(db_index=True, unique=True, verbose_name=128),
        ),
        migrations.AlterField(
            model_name='decisiontreecr',
            name='tree',
            field=models.JSONField(validators=[api.validators.DecisionTreeValidator.validate_tree]),
        ),
        migrations.AlterField(
            model_name='queuecr',
            name='name',
            field=models.CharField(db_index=True, unique=True, verbose_name=128),
        ),
    ]
