# Generated by Django 4.2.2 on 2023-06-09 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionTreeCMT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField()),
                ('update_time', models.DateField()),
                ('name', models.CharField(verbose_name=128)),
                ('tree', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='QueueCMT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField()),
                ('update_time', models.DateField()),
                ('name', models.CharField(verbose_name=128)),
                ('prioritization_function', models.JSONField()),
                ('decision_tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.decisiontreecmt')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewCMT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField()),
                ('update_time', models.DateField()),
                ('entity_id', models.CharField(verbose_name=128)),
                ('entity_type', models.CharField(verbose_name=128)),
                ('entity_create_time', models.DateField()),
                ('entity_metadata', models.JSONField()),
                ('user_id', models.CharField(verbose_name=128)),
                ('user_name', models.CharField(verbose_name=128)),
                ('user_email', models.CharField(verbose_name=128)),
                ('user_phone_number', models.CharField(verbose_name=128)),
                ('user_metadata', models.JSONField()),
                ('questions_with_answers', models.JSONField()),
                ('score', models.FloatField()),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.queuecmt')),
            ],
        ),
    ]
