# Generated by Django 4.2.2 on 2023-06-10 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuecmt',
            name='decision_tree',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.decisiontreecmt'),
        ),
        migrations.AlterField(
            model_name='queuecmt',
            name='prioritization_function',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='reviewcmt',
            name='entity_create_time',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='reviewcmt',
            name='entity_id',
            field=models.CharField(blank=True, default=None, null=True, verbose_name=128),
        ),
        migrations.AlterField(
            model_name='reviewcmt',
            name='entity_metadata',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='reviewcmt',
            name='entity_type',
            field=models.CharField(blank=True, default=None, null=True, verbose_name=128),
        ),
        migrations.AlterField(
            model_name='reviewcmt',
            name='questions_with_answers',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='reviewcmt',
            name='queue',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.queuecmt'),
        ),
        migrations.AlterField(
            model_name='reviewcmt',
            name='score',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='reviewcmt',
            name='user_email',
            field=models.CharField(blank=True, default=None, null=True, verbose_name=128),
        ),
        migrations.AlterField(
            model_name='reviewcmt',
            name='user_id',
            field=models.CharField(blank=True, default=None, null=True, verbose_name=128),
        ),
        migrations.AlterField(
            model_name='reviewcmt',
            name='user_metadata',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='reviewcmt',
            name='user_name',
            field=models.CharField(blank=True, default=None, null=True, verbose_name=128),
        ),
        migrations.AlterField(
            model_name='reviewcmt',
            name='user_phone_number',
            field=models.CharField(blank=True, default=None, null=True, verbose_name=128),
        ),
    ]
