# Generated by Django 4.2.2 on 2023-06-10 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_queuecmt_decision_tree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisiontreecmt',
            name='create_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='decisiontreecmt',
            name='update_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='queuecmt',
            name='create_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='queuecmt',
            name='update_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reviewcmt',
            name='create_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reviewcmt',
            name='entity_create_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='reviewcmt',
            name='update_time',
            field=models.DateTimeField(),
        ),
    ]
